/**
 * M365Relay S0 live observer.
 *
 * This runner is deliberately isolated from the product request path. It uses
 * the existing owned-Edge/CDP guard and the current M365 DOM selectors, then
 * records only hashes, relative evidence paths and stage outcomes. It never
 * reads cookies, credentials or browser storage.
 *
 * Usage (from the repository root):
 *   node spikes/s0/live.mjs <trial-directory>
 *
 * The trial directory is normally generated by the attached spike.mjs
 * prepare command. The runner refuses to overwrite an existing observation
 * file and never uses operator-only/P2 as a recovery source.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, rename, stat, writeFile } from 'node:fs/promises';
import { basename, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { loadConfig } from '../../src/config.mjs';
import { connectOwnedBrowser } from '../../src/cdp.mjs';
import { domExpression } from '../../src/dom.mjs';
import { attachmentState } from '../../src/image-attachments.mjs';

const CASES = ['P1-v1', 'P1-v2', 'P2-direct', 'P3-body', 'P4-file'];
const CHECKER_BASE = 'https://m365.cloud.microsoft';
const sleep = ms => new Promise(resolveSleep => setTimeout(resolveSleep, ms));
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const now = () => new Date().toISOString();

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

async function fileHash(path) {
  const bytes = await readFile(path);
  return { bytes: bytes.length, sha256: sha256(bytes) };
}

async function writeNew(path, value) {
  await writeFile(path, value, { flag: 'wx', mode: 0o600 });
}

async function evaluate(browser, sessionId, expression, signal) {
  const result = await browser.send('Runtime.evaluate', {
    expression,
    returnByValue: true,
    userGesture: true,
  }, sessionId, signal, 15000);
  assert(!result.exceptionDetails, 'M365 DOM evaluation failed');
  assert(result.result && Object.hasOwn(result.result, 'value'), 'M365 DOM result missing');
  return result.result.value;
}

async function dom(browser, sessionId, config, operation, args, signal) {
  const result = await evaluate(browser, sessionId, domExpression(config, operation, args), signal);
  if (result && result.__m365_relay_dom_error__) {
    throw new Error(`M365 DOM changed: ${result.__m365_relay_dom_error__.reason}`);
  }
  return result;
}

async function selectM365Page(browser, signal) {
  const { targetInfos } = await browser.send('Target.getTargets', {}, undefined, signal);
  const pages = (targetInfos ?? []).filter(target => target.type === 'page');
  const candidates = pages.filter(target => {
    try { return new URL(target.url).origin === CHECKER_BASE; } catch { return false; }
  });
  assert(candidates.length === 1, `Expected exactly one M365 page, found ${candidates.length}`);
  const { sessionId } = await browser.send('Target.attachToTarget', {
    targetId: candidates[0].targetId,
    flatten: true,
  }, undefined, signal);
  return { target: candidates[0], sessionId };
}

async function openInspectionPage(browser, url, signal) {
  const { targetId } = await browser.send('Target.createTarget', { url, background: false }, undefined, signal);
  try {
    const { sessionId } = await browser.send('Target.attachToTarget', { targetId, flatten: true }, undefined, signal);
    await sleep(2000);
    return { targetId, sessionId };
  } catch (error) {
    await browser.send('Target.closeTarget', { targetId }, undefined, signal).catch(() => {});
    throw error;
  }
}

async function waitUntil(label, action, { timeoutMs = 30000, intervalMs = 250 } = {}) {
  const deadline = Date.now() + timeoutMs;
  let last;
  while (Date.now() < deadline) {
    last = await action();
    if (last) return last;
    await sleep(intervalMs);
  }
  throw new Error(`Timed out waiting for ${label}`);
}

async function snapshot(browser, sessionId, config, signal) {
  return dom(browser, sessionId, config, 'snapshot', {}, signal);
}

async function ensureEmpty(browser, sessionId, config, signal) {
  let state = await snapshot(browser, sessionId, config, signal);
  if (state.editor && !state.nonempty && !state.input.trim() && !state.busy) return {
    observed: true,
    conversationReset: false,
  };
  // The current Copilot surface renders the sidebar action as an <a> while
  // the compact header variant is a <button>; support both without changing
  // the product selector contract.
  const created = await evaluate(browser, sessionId, `(()=>{const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};const label=e=>(e.getAttribute('aria-label')||e.title||e.textContent||'').trim();const nodes=[...document.querySelectorAll('button,a,[role="button"]')].filter(e=>visible(e)&&/^(新しいチャット|新規チャット|New chat|Start a new chat)$/i.test(label(e)));if(nodes.length!==1)return {clicked:false,count:nodes.length};nodes[0].click();return {clicked:true}})()`, signal);
  assert(created?.clicked, 'New chat control was not available');
  await waitUntil('empty new conversation', async () => {
    state = await snapshot(browser, sessionId, config, signal);
    return state.editor && !state.nonempty && !state.input.trim() && !state.busy ? true : null;
  });
  return { observed: true, conversationReset: true };
}

async function attachmentSnapshot(browser, sessionId, config, names, signal) {
  const expression = `(${attachmentState.toString()})(${JSON.stringify(config.origin)},${JSON.stringify(names)})`;
  const state = await evaluate(browser, sessionId, expression, signal);
  assert(!state?.wrongOrigin, 'Attachment page origin changed');
  return state;
}

function editorCheckExpression(config, expected) {
  return `(()=>{const selectors=${JSON.stringify(config.selectors.editor)};const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};const nodes=selectors.flatMap(s=>[...document.querySelectorAll(s)]).filter(visible);const editor=[...new Set(nodes)];if(editor.length!==1)return {matched:false,reason:'editor_not_unique',observed_chars:0,expected_chars:${JSON.stringify(expected.length)}};const e=editor[0];const raw=typeof e.value==='string'?e.value:(e.textContent||'');const text=raw.replace(/\\r\\n?/g,'\\n').replace(/[\\u200B\\u200C]+$/g,'');const want=${JSON.stringify(expected)};let i=0;while(i<text.length&&i<want.length&&text[i]===want[i])i++;return {matched:text===want,observed_chars:text.length,expected_chars:want.length,first_difference:text===want?null:i,reader:typeof e.value==='string'?'value':'contenteditable-textContent'}})()`;
}

function sendReadyExpression(config, expected) {
  return `(()=>{const check=${editorCheckExpression(config, expected)};if(!check.matched)return {ready:false,input:check};const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};const label=e=>(e.getAttribute('aria-label')||e.title||e.textContent||'').trim();const selectors=${JSON.stringify(config.selectors.send)};const nodes=selectors.flatMap(s=>[...document.querySelectorAll(s)]).filter(visible);const exact=[...new Set(nodes)];const buttons=exact.length?[...new Set(exact)]:[...document.querySelectorAll('button,[role="button"]')].filter(e=>visible(e)&&/^(送信|送信する|Send|Send message|Send prompt)(?:\\s*\\([^)]*\\))?$/i.test(label(e)));const button=buttons.length===1?buttons[0]:null;const stop=[...document.querySelectorAll('button,[role="button"]')].some(e=>visible(e)&&/^(停止|生成を停止|応答の生成を停止|Stop|Stop generating|Stop responding)$/i.test(label(e)));return {ready:!!button&&!button.disabled&&button.getAttribute('aria-disabled')!=='true'&&!stop,input:check,button_found:!!button,busy:stop}})()`;
}

function sendExpression(config, expected) {
  return `(()=>{const ready=${sendReadyExpression(config, expected)};if(!ready.input?.matched||!ready.ready)return {clicked:false,input:ready.input,ready:ready.ready};const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};const label=e=>(e.getAttribute('aria-label')||e.title||e.textContent||'').trim();const selectors=${JSON.stringify(config.selectors.send)};const nodes=selectors.flatMap(s=>[...document.querySelectorAll(s)]).filter(visible);const button=([...new Set(nodes)].length===1?[...new Set(nodes)][0]:[...document.querySelectorAll('button,[role="button"]')].find(e=>visible(e)&&/^(送信|送信する|Send|Send message|Send prompt)(?:\\s*\\([^)]*\\))?$/i.test(label(e))));if(!button||button.disabled||button.getAttribute('aria-disabled')==='true')return {clicked:false,ready:false,input:ready.input};button.click();return {clicked:true,ready:true,input:ready.input}})()`;
}

async function attachFile(browser, sessionId, config, path, signal) {
  const name = basename(path);
  const before = await attachmentSnapshot(browser, sessionId, config, [name], signal);
  assert(before.attachmentCount === 0, 'Existing attachment is present; refusing to add another');
  const { root } = await browser.send('DOM.getDocument', {}, sessionId, signal);
  const { nodeIds } = await browser.send('DOM.querySelectorAll', {
    nodeId: root.nodeId,
    selector: 'input#upload-file-button[type="file"]',
  }, sessionId, signal);
  assert(nodeIds?.length === 1, 'File input was not uniquely found');
  await browser.send('DOM.setFileInputFiles', { nodeId: nodeIds[0], files: [resolve(path)] }, sessionId, signal, 30000);
  const attached = await waitUntil(`attachment ${name}`, async () => {
    const state = await attachmentSnapshot(browser, sessionId, config, [name], signal);
    return state.attached?.[0] && state.attachmentCount === 1 && !state.pending ? state : null;
  }, { timeoutMs: 45000, intervalMs: 300 });
  return { file_name: name, sha256: (await fileHash(path)).sha256, bytes: (await fileHash(path)).bytes, state: attached };
}

async function insertAndSend(browser, sessionId, config, prompt, signal) {
  const before = await evaluate(browser, sessionId, editorCheckExpression(config, ''), signal);
  assert(before?.matched, 'Editor was not empty before prompt insertion');
  const focus = await dom(browser, sessionId, config, 'focus', { stableMs: 0 }, signal);
  assert(focus?.focused, 'M365 editor focus failed');
  await browser.send('Input.insertText', { text: prompt }, sessionId, signal, 30000);
  await waitUntil('prompt reconciliation', async () => {
    const check = await evaluate(browser, sessionId, editorCheckExpression(config, prompt), signal);
    return check?.matched ? check : null;
  }, { timeoutMs: 15000, intervalMs: 100 });
  await waitUntil('send button readiness', async () => {
    const ready = await evaluate(browser, sessionId, sendReadyExpression(config, prompt), signal);
    if (ready?.input && !ready.input.matched) throw new Error('Prompt changed before send');
    return ready?.ready ? ready : null;
  }, { timeoutMs: 20000, intervalMs: 150 });
  const clicked = await evaluate(browser, sessionId, sendExpression(config, prompt), signal);
  assert(clicked?.clicked, 'Send click was not confirmed');
  return { prompt_chars: prompt.length, sent_at: now() };
}

async function waitReply(browser, sessionId, config, signal, { structured = false } = {}) {
  let lastKey = '';
  let stableSince = 0;
  return waitUntil('assistant response', async () => {
    const reply = await evaluate(browser, sessionId, `(()=>{const requireStructured=${structured ? 'true' : 'false'};const sels=${JSON.stringify(config.selectors.assistant)};const label=e=>(e.getAttribute('aria-label')||e.title||e.textContent||'').trim();const busy=[...document.querySelectorAll('button,[role="button"]')].some(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'&&/^(停止|生成を停止|応答の生成を停止|Stop|Stop generating|Stop responding)$/i.test(label(e))});if(busy)return {candidates:[],nonempty:false,busy:true};const nodes=sels.flatMap(s=>[...document.querySelectorAll(s)]);for(let i=nodes.length-1;i>=0;i--){const n=nodes[i];const indexed=[...n.querySelectorAll('[data-line-index]')];if(indexed.length&&indexed.every((e,j)=>e.getAttribute('data-line-index')===String(j))){const body=indexed.map(e=>e.textContent||'').join('\\n').trim();if(/^S0_RESULT\\s+[a-f0-9-]{36}\\n/.test(body)){if(!/\\nEND_S0_RESULT$/.test(body))return {candidates:[],nonempty:false,busy:true,partial:true};return {candidates:[body],nonempty:true,structured:true};}if(body&&!requireStructured)return {candidates:[body],nonempty:true};}const pre=[...n.querySelectorAll('pre code,pre')].map(e=>(e.textContent||'').trim()).filter(Boolean);if(pre.length){const structuredText=pre.find(text=>/^S0_RESULT\\s+[a-f0-9-]{36}\\n/.test(text));if(structuredText&&!/\\nEND_S0_RESULT$/.test(structuredText))return {candidates:[],nonempty:false,busy:true,partial:true};if(requireStructured&&!structuredText)return {candidates:[],nonempty:false,busy:true,partial:true};return {candidates:[...new Set(pre)],nonempty:true};}const text=(n.innerText||n.textContent||'').trim();if(requireStructured&&!/^S0_RESULT\\s+[a-f0-9-]{36}\\n/.test(text))continue;if(/S0_RESULT\\s+[a-f0-9-]{36}/.test(text)&&!/END_S0_RESULT/.test(text))return {candidates:[],nonempty:false,busy:true,partial:true};if(text)return {candidates:[text],nonempty:true};}return {candidates:[],nonempty:false,busy:false}})()`, signal);
    if (reply.busy || !reply.nonempty || !reply.candidates?.length) {
      lastKey = '';
      stableSince = 0;
      return null;
    }
    const key = JSON.stringify(reply.candidates);
    if (key !== lastKey) {
      lastKey = key;
      stableSince = Date.now();
      return null;
    }
    if (Date.now() - stableSince < 1000) return null;
    return { candidates: reply.candidates, captured_at: now() };
  }, { timeoutMs: 180000, intervalMs: 750 });
}

async function writeCapture(root, name, text) {
  const path = join(root, 'captures', name);
  await writeNew(path, Buffer.from(text, 'utf8'));
  return { path: relative(root, path), ...(await fileHash(path)) };
}

async function inspectDownloadables(browser, sessionId, signal) {
  return evaluate(browser, sessionId, `(()=>[...document.querySelectorAll('a,button,[role="button"]')].map((e,index)=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {index,tag:e.tagName,text:(e.innerText||e.textContent||'').trim().slice(0,200),aria:e.getAttribute('aria-label'),title:e.getAttribute('title'),download:e.getAttribute('download'),href:e.tagName==='A'?e.href:null,visible:r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'}}).filter(x=>x.visible&&(x.download!==null||/download|ダウンロード|native-result|handbook|txt/i.test([x.text,x.aria,x.title,x.download,x.href].filter(Boolean).join(' ')))) )()`, signal);
}

async function downloadCandidate(browser, sessionId, downloadDir, candidates, preferred, signal) {
  const candidate = candidates.find(item => [item.text, item.aria, item.title, item.download, item.href].filter(Boolean).join(' ').toLowerCase().includes(preferred.toLowerCase())) || candidates.find(item => item.download !== null);
  if (!candidate) return null;
  await mkdir(downloadDir, { recursive: true, mode: 0o700 });
  await browser.send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: resolve(downloadDir) }, undefined, signal);
  const clicked = await evaluate(browser, sessionId, `(()=>{const all=[...document.querySelectorAll('a,button,[role="button"]')];const e=all[${candidate.index}];if(!e)return false;e.click();return true})()`, signal);
  assert(clicked === true, 'Download candidate disappeared before click');
  const file = await waitUntil('downloaded artifact', async () => {
    const names = await readdir(downloadDir);
    const usable = names.filter(name => !name.endsWith('.crdownload') && name !== 'download.metadata');
    if (!usable.length) return null;
    const path = join(downloadDir, usable[0]);
    const info = await stat(path);
    return info.size > 0 ? path : null;
  }, { timeoutMs: 30000, intervalMs: 500 });
  return file;
}

async function waitForDownloadables(browser, sessionId, signal, preferred) {
  try {
    return await waitUntil(`downloadable ${preferred}`, async () => {
      const candidates = await inspectDownloadables(browser, sessionId, signal);
      const exact = candidates.find(item => [item.text, item.aria, item.title, item.download, item.href].filter(Boolean).join(' ').toLowerCase().includes(preferred.toLowerCase()));
      return exact ? candidates : null;
    }, { timeoutMs: 20000, intervalMs: 500 });
  } catch {
    return [];
  }
}

async function copilotSourceLink(browser, sessionId, fileName, signal) {
  return waitUntil(`Copilot source link ${fileName}`, async () => {
    const href = await evaluate(browser, sessionId, `(()=>{const v=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'};const a=[...document.querySelectorAll('a')].find(e=>v(e)&&(e.textContent||'').trim()===${JSON.stringify(fileName)}&&/^https:\\/\\/onedrive\\.live\\.com\\//i.test(e.href));return a?.href||null})()`, signal).catch(() => null);
    return href || null;
  }, { timeoutMs: 30000, intervalMs: 500 });
}

async function recoverOneDriveAttachment(browser, sourceUrl, downloadDir, signal) {
  const { targetId } = await browser.send('Target.createTarget', { url: sourceUrl, background: false }, undefined, signal);
  let sessionId;
  try {
    ({ sessionId } = await browser.send('Target.attachToTarget', { targetId, flatten: true }, undefined, signal));
    await waitUntil('OneDrive viewer', async () => {
      const state = await evaluate(browser, sessionId, `(()=>({href:location.href,host:location.hostname,title:document.title,overflow:!!document.querySelector('[data-automationid="overflowButton"]')}))()`, signal);
      if (/^(login|account)\\./i.test(state.host)) throw new Error('OneDrive sign-in is required; no authentication was automated');
      return state.host === 'onedrive.live.com' && state.overflow ? state : null;
    }, { timeoutMs: 30000, intervalMs: 500 });
    await mkdir(downloadDir, { recursive: true, mode: 0o700 });
    await browser.send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: resolve(downloadDir) }, undefined, signal);
    await browser.send('Page.setDownloadBehavior', { behavior: 'allow', downloadPath: resolve(downloadDir) }, sessionId, signal).catch(() => {});
    const opened = await evaluate(browser, sessionId, `(()=>{const e=document.querySelector('[data-automationid="overflowButton"]');if(!e)return false;e.click();return true})()`, signal);
    assert(opened, 'OneDrive action menu was not available');
    const download = await waitUntil('OneDrive download action', async () => evaluate(browser, sessionId, `(()=>{const e=document.querySelector('button[data-automationid="download"]');const r=e?.getBoundingClientRect(),s=e&&getComputedStyle(e);return e&&r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled})()`, signal), { timeoutMs: 10000, intervalMs: 300 });
    assert(download, 'OneDrive download action was not available');
    const point = await evaluate(browser, sessionId, `(()=>{const e=document.querySelector('button[data-automationid="download"]');if(!e)return null;const r=e.getBoundingClientRect();e.focus();return {x:r.left+r.width/2,y:r.top+r.height/2,focused:document.activeElement===e}})()`, signal);
    assert(point && Number.isFinite(point.x) && Number.isFinite(point.y), 'OneDrive download action disappeared before click');
    await browser.send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13 }, sessionId, signal);
    await browser.send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13 }, sessionId, signal);
    await sleep(500);
    const startedByKey = (await readdir(downloadDir)).some(name => name !== 'download.metadata');
    if (startedByKey) return await waitUntil('OneDrive downloaded attachment', async () => {
      const names = await readdir(downloadDir);
      const usable = names.filter(name => !name.endsWith('.crdownload') && name !== 'download.metadata');
      if (!usable.length) return null;
      const path = join(downloadDir, usable[0]);
      const info = await stat(path);
      return info.size > 0 ? path : null;
    }, { timeoutMs: 30000, intervalMs: 500 });
    await browser.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: point.x, y: point.y, button: 'none' }, sessionId, signal);
    await browser.send('Input.dispatchMouseEvent', { type: 'mousePressed', x: point.x, y: point.y, button: 'left', buttons: 1, clickCount: 1 }, sessionId, signal);
    await browser.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: point.x, y: point.y, button: 'left', buttons: 0, clickCount: 1 }, sessionId, signal);
    return await waitUntil('OneDrive downloaded attachment', async () => {
      const names = await readdir(downloadDir);
      const usable = names.filter(name => !name.endsWith('.crdownload') && name !== 'download.metadata');
      if (!usable.length) return null;
      const path = join(downloadDir, usable[0]);
      const info = await stat(path);
      return info.size > 0 ? path : null;
    }, { timeoutMs: 30000, intervalMs: 500 });
  } finally {
    await browser.send('Target.closeTarget', { targetId }, undefined, signal).catch(() => {});
  }
}

async function settledConversationUrl(browser, sessionId, signal) {
  try {
    return await waitUntil('conversation URL', async () => {
      const href = await evaluate(browser, sessionId, 'location.href', signal);
      return /\/conversation\/[0-9a-f-]{36}$/i.test(href) ? href : null;
    }, { timeoutMs: 10000, intervalMs: 250 });
  } catch {
    return await evaluate(browser, sessionId, 'location.href', signal);
  }
}

function routeTemplate(caseId) {
  return {
    case_id: caseId,
    status: 'NOT_RUN',
    source_acquisition: { mode: 'not_observed', evidence: [] },
    destination_supply: { mode: 'not_observed', evidence: [] },
    response_capture: { mode: 'not_observed', evidence: [] },
    conversation_a: null,
    conversation_b: null,
    distinct_empty_destination_observed: null,
    fixture_version_observed: null,
    captured_artifact: null,
    content_check_report: null,
    elapsed_ms: null,
    sends: null,
    human_interventions: null,
    failure_stage: null,
    note: null,
  };
}

async function main() {
  const trial = resolve(process.argv[2] ?? '');
  assert(trial && trial !== resolve('.'), 'Usage: node spikes/s0/live.mjs <trial-directory>');
  const observationPath = join(trial, 'observations.json');
  const observations = JSON.parse(await readFile(observationPath, 'utf8'));
  assert(observations.live_m365_executed === false, 'This trial already contains live observations');
  const manifest = JSON.parse(await readFile(join(trial, 'assessor-only', 'manifest.json'), 'utf8'));
  const checker = await import(pathToFileURL(join(trial, '..', 'spike.mjs')).href);
  const config = await loadConfig();
  const signal = AbortSignal.timeout(20 * 60 * 1000);
  const browser = await connectOwnedBrowser(config, signal);
  const { target, sessionId } = await selectM365Page(browser, signal);
  const started = Date.now();
  const routes = Object.fromEntries(CASES.map(caseId => [caseId, routeTemplate(caseId)]));
  let sends = 0;
  let interventions = 0;
  try {
    observations.live_m365_executed = true;
    observations.environment = {
      os: process.platform,
      edge_version: null,
      relay_commit: observations.base_commit,
      copilot_surface: target.url,
      observed_mode: 'regular M365 Copilot chat',
      profile_alias: 'M365Relay dedicated Edge profile',
      memory_setting_observed: null,
      observer: 'Codex',
      observed_at: now(),
    };
    const version = await fetch(`http://127.0.0.1:${config.cdpPort}/json/version`, { signal }).then(response => response.json());
    observations.environment.edge_version = version.Browser ?? null;

    const prompt = async name => readFile(join(trial, 'prompts', name), 'utf8');
    const source = async relativePath => join(trial, relativePath);
    const runA = async (caseId, filePath, promptName, { direct = false } = {}) => {
      const route = routes[caseId];
      const started = Date.now();
      const empty = await ensureEmpty(browser, sessionId, config, signal);
      route.distinct_empty_destination_observed = empty.observed;
      const attachment = await attachFile(browser, sessionId, config, filePath, signal);
      route.source_acquisition = { mode: direct ? 'operator_direct_attachment' : 'automated_fixture_upload', evidence: [{ file_name: attachment.file_name, source_sha256: attachment.sha256, bytes: attachment.bytes }] };
      if (direct) interventions += 1;
      const sent = await insertAndSend(browser, sessionId, config, await prompt(promptName), signal);
      sends += 1;
      route.sends = (route.sends ?? 0) + 1;
      route.human_interventions = (route.human_interventions ?? 0) + (direct ? 1 : 0);
      const reply = await waitReply(browser, sessionId, config, signal, { structured: /-B\.txt$/.test(promptName) || caseId === 'P3-body' });
      const conversationUrl = await settledConversationUrl(browser, sessionId, signal);
      route.conversation_a = { target_id: target.targetId, conversation_url: conversationUrl, prompt_file: promptName, prompt_chars: sent.prompt_chars, sent_at: sent.sent_at };
      const capture = await writeCapture(trial, `${caseId}-A.txt`, reply.candidates[0]);
      route.response_capture = { mode: 'automated_assistant_dom', evidence: [capture] };
      route.elapsed_ms = (route.elapsed_ms ?? 0) + (Date.now() - started);
      return { reply, capture };
    };
    const runB = async (caseId, filePath, promptName, { artifactMode = 'automated_resupply' } = {}) => {
      const route = routes[caseId];
      const started = Date.now();
      const empty = await ensureEmpty(browser, sessionId, config, signal);
      route.distinct_empty_destination_observed = route.distinct_empty_destination_observed === null
        ? empty.observed
        : route.distinct_empty_destination_observed && empty.observed;
      route.destination_supply = { mode: artifactMode, evidence: [] };
      const attachment = await attachFile(browser, sessionId, config, filePath, signal);
      if (route.source_acquisition.mode === 'not_observed') {
        route.source_acquisition = { mode: 'automated_fixture_upload', evidence: [{ file_name: attachment.file_name, source_sha256: attachment.sha256, bytes: attachment.bytes }] };
      }
      route.destination_supply.evidence.push({ file_name: attachment.file_name, supplied_sha256: attachment.sha256, bytes: attachment.bytes });
      const sent = await insertAndSend(browser, sessionId, config, await prompt(promptName), signal);
      sends += 1;
      route.sends = (route.sends ?? 0) + 1;
      const reply = await waitReply(browser, sessionId, config, signal, { structured: true });
      const conversationUrl = await settledConversationUrl(browser, sessionId, signal);
      route.conversation_b = { target_id: target.targetId, conversation_url: conversationUrl, prompt_file: promptName, prompt_chars: sent.prompt_chars, sent_at: sent.sent_at };
      const capture = await writeCapture(trial, `${caseId}-B.txt`, reply.candidates[0]);
      route.response_capture.mode = route.response_capture.mode === 'not_observed' ? 'automated_assistant_dom' : route.response_capture.mode;
      route.response_capture.evidence.push(capture);
      route.elapsed_ms = (route.elapsed_ms ?? 0) + (Date.now() - started);
      return { reply, capture };
    };

    const p1v1A = await runA('P1-v1', await source('inputs/P1/v1/reference.txt'), 'P1-v1-A.txt');
    await runB('P1-v1', await source('inputs/P1/v1/reference.txt'), 'P1-v1-B.txt');
    routes['P1-v1'].fixture_version_observed = { source_sha256: manifest.cases['P1-v1'].source_sha256, revision_label: 'v1' };
    await runB('P1-v2', await source('inputs/P1/v2/reference.txt'), 'P1-v2-B.txt');
    routes['P1-v2'].fixture_version_observed = { source_sha256: manifest.cases['P1-v2'].source_sha256, revision_label: 'v2' };

    await runA('P2-direct', await source('operator-only/P2/handbook.txt'), 'P2-direct-A.txt', { direct: true });
    let p2SourceUrl = null;
    let p2Candidates = [];
    let p2Inspection;
    try {
      // Re-open the recorded A conversation so the source card has time to
      // hydrate independently of the main page's route transition.
      p2Inspection = await openInspectionPage(browser, routes['P2-direct'].conversation_a.conversation_url, signal);
      p2SourceUrl = await copilotSourceLink(browser, p2Inspection.sessionId, 'handbook.txt', signal);
      p2Candidates = p2SourceUrl ? await inspectDownloadables(browser, p2Inspection.sessionId, signal) : [];
    } catch {}
    if (p2Inspection) await browser.send('Target.closeTarget', { targetId: p2Inspection.targetId }, undefined, signal).catch(() => {});
    routes['P2-direct'].note = { downloadable_candidates_observed: p2Candidates, source_link_observed: !!p2SourceUrl, source_host: p2SourceUrl ? 'onedrive.live.com' : null };
    const p2Download = p2SourceUrl
      ? await recoverOneDriveAttachment(browser, p2SourceUrl, join(trial, 'downloads', 'P2-direct'), signal).catch(() => null)
      : await downloadCandidate(browser, sessionId, join(trial, 'downloads', 'P2-direct'), p2Candidates, 'handbook.txt', signal).catch(() => null);
    if (!p2Download) {
      routes['P2-direct'].status = 'FAIL';
      routes['P2-direct'].failure_stage = 'recovery';
      routes['P2-direct'].note = { downloadable_candidates_observed: p2Candidates, source_link_observed: !!p2SourceUrl, source_host: p2SourceUrl ? 'onedrive.live.com' : null, failure: 'Copilot UI exposed no verified downloadable/recapturable handbook artifact; operator-only source was not reused.' };
    } else {
      const recovered = join(trial, 'captures', 'recovered-handbook.txt');
      await rename(p2Download, recovered);
      routes['P2-direct'].captured_artifact = { mode: 'downloaded_from_copilot_ui', path: relative(trial, recovered), ...(await fileHash(recovered)) };
      await runB('P2-direct', recovered, 'P2-direct-B.txt');
    }

    await runA('P3-body', await source('inputs/P3/body-source.txt'), 'P3-body-A.txt');
    const p3Body = routes['P3-body'].response_capture.evidence[0];
    const capturedReplyPath = join(trial, 'captures', 'captured-reply.txt');
    await rename(join(trial, p3Body.path), capturedReplyPath);
    routes['P3-body'].captured_artifact = { mode: 'assistant_body_saved_by_observer', path: relative(trial, capturedReplyPath), ...(await fileHash(capturedReplyPath)) };
    await runB('P3-body', capturedReplyPath, 'P3-body-B.txt');

    await runA('P4-file', await source('inputs/P4/file-source.txt'), 'P4-file-A.txt');
    const p4Candidates = await waitForDownloadables(browser, sessionId, signal, 'native-result.txt');
    routes['P4-file'].note = { downloadable_candidates_observed: p4Candidates };
    const p4Download = await downloadCandidate(browser, sessionId, join(trial, 'downloads', 'P4-file'), p4Candidates, 'native-result.txt', signal).catch(() => null);
    if (!p4Download) {
      routes['P4-file'].status = 'UNSUPPORTED';
      routes['P4-file'].failure_stage = 'recovery';
      routes['P4-file'].note = { downloadable_candidates_observed: p4Candidates, failure: 'This Copilot surface did not expose a verifiable native-result.txt download.' };
    } else {
      const nativeResult = join(trial, 'captures', 'native-result.txt');
      await rename(p4Download, nativeResult);
      routes['P4-file'].captured_artifact = { mode: 'copilot_native_download', path: relative(trial, nativeResult), ...(await fileHash(nativeResult)) };
      await runB('P4-file', nativeResult, 'P4-file-B.txt');
    }

    const checkCapture = async (caseId, captureName, reportName) => {
      const route = routes[caseId];
      const capturePath = join(trial, 'captures', captureName);
      try {
        const report = await checker.check(trial, caseId, capturePath);
        const reportPath = join(trial, 'checks', reportName);
        await writeNew(reportPath, JSON.stringify(report, null, 2) + '\n');
        route.content_check_report ??= {};
        route.content_check_report[captureName] = { path: relative(trial, reportPath), ...report };
        return report;
      } catch (error) {
        route.content_check_report ??= {};
        route.content_check_report[captureName] = { content_check: 'ERROR', error: error?.message ?? String(error) };
        return { content_check: 'FAIL', error: error?.message ?? String(error) };
      }
    };
    const p1v1 = await checkCapture('P1-v1', 'P1-v1-B.txt', 'P1-v1-B.json');
    const p1v2 = await checkCapture('P1-v2', 'P1-v2-B.txt', 'P1-v2-B.json');
    const p2 = routes['P2-direct'].captured_artifact ? await checkCapture('P2-direct', 'P2-direct-B.txt', 'P2-direct-B.json') : null;
    const p3a = await checkCapture('P3-body', 'captured-reply.txt', 'P3-body-A.json');
    const p3b = await checkCapture('P3-body', 'P3-body-B.txt', 'P3-body-B.json');
    const p4a = routes['P4-file'].captured_artifact ? await checkCapture('P4-file', 'native-result.txt', 'P4-file-A.json') : null;
    const p4b = routes['P4-file'].captured_artifact ? await checkCapture('P4-file', 'P4-file-B.txt', 'P4-file-B.json') : null;
    routes['P1-v1'].status = p1v1.content_check === 'PASS' ? 'PASS' : 'FAIL';
    routes['P1-v2'].status = p1v2.content_check === 'PASS' ? 'PASS' : 'FAIL';
    if (routes['P2-direct'].status !== 'FAIL') routes['P2-direct'].status = p2?.content_check === 'PASS' ? 'PASS' : 'FAIL';
    routes['P3-body'].status = p3a.content_check === 'PASS' && p3b.content_check === 'PASS' ? 'PASS' : 'FAIL';
    if (routes['P4-file'].status !== 'UNSUPPORTED') routes['P4-file'].status = p4a?.content_check === 'PASS' && p4b?.content_check === 'PASS' ? 'PASS' : 'FAIL';
  } catch (error) {
    const current = Object.values(routes).find(route => route.status === 'NOT_RUN');
    if (current) {
      current.status = 'BLOCKED';
      current.failure_stage ??= 'live_execution';
      current.note = error instanceof Error ? error.message : String(error);
    }
    throw error;
  } finally {
    observations.cases = CASES.map(caseId => routes[caseId]);
    observations.environment.observed_at ??= now();
    observations.elapsed_ms = Date.now() - started;
    observations.sends = sends;
    observations.human_interventions = interventions;
    observations.note = '実M365の取得・新規会話への供給・回答/生成物回収を観測。content_checkは別コマンドの結果を後から紐付ける。';
    await writeFile(observationPath, JSON.stringify(observations, null, 2) + '\n', { flag: 'w', mode: 0o600 });
    browser.close();
  }
  console.log(JSON.stringify({ trial, statuses: Object.fromEntries(CASES.map(caseId => [caseId, routes[caseId].status])), sends, human_interventions: interventions }, null, 2));
}

export { recoverOneDriveAttachment, copilotSourceLink, inspectDownloadables };

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch(error => {
    console.error(error?.message ?? String(error));
    process.exitCode = 1;
  });
}
